app = 'chrozone'
primary_region = 'sin'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[[http_service.checks]]
grace_period = "5s"
interval = "10s"
timeout = "5s"
method = "GET"
path = "/"

[[vm]]
size = 'shared-cpu-1x'
